cookie:
  expiry_days: 30
  key: some_signature_key # Must be a string
  name: some_cookie_name
credentials:
  usernames:
    thinhnp:
      email: ThinhNP@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Thinh
      last_name: Nguyen Phuc
      logged_in: False # Will be managed automatically
      password: abc@123 # Will be hashed automatically
      roles: # Optional
      - admin
      - editor
      - viewer
    vanoai:
      email: vanoai@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Oai
      last_name: Nguyen Van
      logged_in: False # Will be managed automatically
      password: abc@123 # Will be hashed automatically
      roles: # Optional
      - viewer
    thuthao:
      email: thuthao@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Thao
      last_name: Vo Thi Thu
      logged_in: False # Will be managed automatically
      password: abc@123 # Will be hashed automatically
      roles: # Optional
      - viewer
    dqn:
      email: dqn@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: N
      last_name: D Q N
      logged_in: False # Will be managed automatically
      password: dqn@123 # Will be hashed automatically
      roles: # Optional
      - viewer
    ngocdien:
      email: ngocdien@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Dien
      last_name: Ngoc
      logged_in: False # Will be managed automatically
      password: ngocdien@123 # Will be hashed automatically
      roles: # Optional
      - viewer
    sangnhan:
      email: sangnhan@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Sang
      last_name: Nhan
      logged_in: False # Will be managed automatically
      password: sangnhan@123 # Will be hashed automatically
      roles: # Optional
      - viewer
    hungpham:
      email: hungpham@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Hung  
      last_name: Pham
      logged_in: False # Will be managed automatically
      password: hungpham@123 # Will be hashed automatically
      roles: # Optional
      - viewer
oauth2: # Optional
  google: # Follow instructions: https://developers.google.com/identity/protocols/oauth2
    client_id: # To be filled
    client_secret: # To be filled
    redirect_uri: # URL to redirect to after OAuth2 authentication
  microsoft: # Follow instructions: https://learn.microsoft.com/en-us/graph/auth-register-app-v2
    client_id: # To be filled
    client_secret: # To be filled
    redirect_uri: # URL to redirect to after OAuth2 authentication
    tenant_id: # To be filled
pre-authorized: # Optional
  emails:
  - melsby@gmail.com
